services:
  modolus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modolus-app
    ports:
      - "8080:8080"
    volumes:
      - ./modolus/Data:/app/modolus/Data
    restart: unless-stopped
